name = "cloud-flared"
main = "src/index.ts"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "cloud-flared-cache"
database_id = "b26f9d68-d091-4b50-b424-4db156e20f10"
